// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<img id=\"propic\" src=\"https://f.rcastellotti.dev/propic.jpeg\" alt=\"propic\"><div id=\"links\"><a href=\"https://g.rcastellotti.dev/rc\">/wrk/</a> <a href=\"https://github.com/rcastellotti\">/gh/</a> <a href=\"https://t.me/rcastellotti\">/tg/</a> <a href=\"mailto:me@rcastellotti.dev\">/email/</a></div><p class=\"now\">NOW: learning to keep prod up with nixOS ／ʕ •ᴥ•ʔ／</p><p>Hi, I am Roberto Castellotti, straight outta <a href=\"https://www.google.com/maps/place/Genoa\">Genova, IT.</a> In 2022 I graduated in <a href=\"https://corsi.unige.it/8759\">Computer Science</a> at <a href=\"https://unige.it\">UniGE</a> and enrolled in a Master a in Informatik at <a href=\"https://tum.de\">TUM</a>. A couple exams from the end I dropped out (ask me how I feel about this). I am currently a Software Engineer at <a href=\"https://guardsquare.com\">Guardsquare</a> in <a href=\"https://www.google.com/maps/place/Leuven\">Leuven, BE</a>.</p><p>I am always disassemblying whatever I can put my hands on to understand what's happening and why, since I simply cannot accept <em>\"It Works\"</em>. You know, the <a href=\"https://stallman.org/articles/on-hacking.html\">hacker</a> way.</p><p>I love computers, a couple of humans, and bears. 🐻🏴\u200d☠️🤍</p><small>we'll build creuza de hacker, dw :)</small>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Roberto Castellotti").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
