package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	chromastyles "github.com/alecthomas/chroma/v2/styles"
)

func main() {
	formatter := chromahtml.New(
		chromahtml.WithClasses(true),
		chromahtml.WithModeClasses(true),
		chromahtml.WithCSSComments(false),
	)

	var css bytes.Buffer
	for _, theme := range []struct {
		name string
		mode string
	}{
		{name: "modus-operandi", mode: "light"},
		{name: "modus-vivendi", mode: "dark"},
	} {
		var generated bytes.Buffer
		if err := formatter.WriteCSS(&generated, chromastyles.Get(theme.name)); err != nil {
			fatal("generate %s syntax CSS: %v", theme.name, err)
		}
		scoped := strings.ReplaceAll(generated.String(), ".chroma."+theme.mode, `:root[data-theme="`+theme.mode+`"] .chroma`)
		scoped = strings.ReplaceAll(scoped, ".bg."+theme.mode, `:root[data-theme="`+theme.mode+`"] .bg`)
		css.WriteString(scoped)
	}

	if err := os.WriteFile("static/syntax.css", css.Bytes(), 0o644); err != nil {
		fatal("write syntax CSS: %v", err)
	}
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
